# -*- coding: utf-8 -*-
"""VideoActionClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CSNw0JJxsVysQnXum_VfsiPBxp0de_a

# Video Action Classification

## 1️⃣ Setup & Mount Drive
"""

# =============================
# 1. SETUP
# =============================

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
import numpy as np
import random
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.model_selection import train_test_split
from tqdm import tqdm

"""2️⃣ Download dataset"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#!/bin/bash
!kaggle datasets download abdallahwagih/ucf101-videos

!unzip /content/ucf101-videos.zip

import os
import pandas as pd


DATASET_ROOT = "/content/UCF101"

IMG_SIZE = 224
SEQUENCE_LENGTH = 16
BATCH_SIZE = 4
EPOCHS = 20

train_df = pd.read_csv(os.path.join(DATASET_ROOT, "train.csv"))
test_df  = pd.read_csv(os.path.join(DATASET_ROOT, "test.csv"))

print("Train samples:", len(train_df))
print("Test samples:", len(test_df))
print("Columns:", train_df.columns)

"""4️⃣ Select Subset of Classes"""

ALL_CLASSES = sorted(train_df['tag'].unique())
SELECTED_CLASSES = ALL_CLASSES[:15]   # increase later if stable

print("Using classes:", SELECTED_CLASSES)

train_df = train_df[train_df['tag'].isin(SELECTED_CLASSES)]
test_df  = test_df[test_df['tag'].isin(SELECTED_CLASSES)]

"""Label Encoding"""

label_to_index = {label: idx for idx, label in enumerate(SELECTED_CLASSES)}
index_to_label = {idx: label for label, idx in label_to_index.items()}
NUM_CLASSES = len(SELECTED_CLASSES)

"""Build Path Lists"""

train_paths = []
train_labels = []

for _, row in train_df.iterrows():
    video_path = os.path.join(DATASET_ROOT, "train", row['video_name'])
    train_paths.append(video_path)
    train_labels.append(label_to_index[row['tag']])

val_paths = []
val_labels = []

for _, row in test_df.iterrows():
    video_path = os.path.join(DATASET_ROOT, "test", row['video_name'])
    val_paths.append(video_path)
    val_labels.append(label_to_index[row['tag']])

train_paths = np.array(train_paths)
train_labels = np.array(train_labels)
val_paths = np.array(val_paths)
val_labels = np.array(val_labels)

print("Train videos:", len(train_paths))
print("Validation videos:", len(val_paths))

"""5️⃣ Frame Sampling (Uniform + Jitter)"""

def sample_frames_uniform_jitter(video_path, sequence_length=16):
    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total_frames < sequence_length:
        cap.release()
        return None

    segment_size = total_frames / sequence_length
    frames = []

    for i in range(sequence_length):
        start = int(i * segment_size)
        end = int((i + 1) * segment_size)
        idx = random.randint(start, max(start, end - 1))

        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ret, frame = cap.read()
        if not ret:
            cap.release()
            return None

        frame = cv2.resize(frame, (IMG_SIZE, IMG_SIZE))
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(frame)

    cap.release()
    return np.array(frames)

"""Memory-Safe Generator"""

def video_generator(paths, labels, batch_size=4, training=True):
    while True:
        indices = np.arange(len(paths))
        if training:
            np.random.shuffle(indices)

        for start in range(0, len(paths), batch_size):
            batch_indices = indices[start:start+batch_size]

            batch_videos = []
            batch_labels = []

            for idx in batch_indices:
                frames = sample_frames_uniform_jitter(paths[idx], SEQUENCE_LENGTH)
                if frames is None:
                    continue

                frames = frames / 255.0
                batch_videos.append(frames)
                batch_labels.append(labels[idx])

            if len(batch_videos) > 0:
                yield np.array(batch_videos), np.array(batch_labels)

"""Create Generators"""

train_gen = video_generator(train_paths, train_labels, BATCH_SIZE, training=True)
val_gen = video_generator(val_paths, val_labels, BATCH_SIZE, training=False)

steps_per_epoch = len(train_paths) // BATCH_SIZE
val_steps = len(val_paths) // BATCH_SIZE

"""8️⃣ Build End-to-End Model (TimeDistributed CNN + GRU)"""

base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

base_model.trainable = False

model = models.Sequential([
    layers.Input(shape=(SEQUENCE_LENGTH, IMG_SIZE, IMG_SIZE, 3)),
    layers.TimeDistributed(base_model),
    layers.TimeDistributed(layers.GlobalAveragePooling2D()),
    layers.GRU(256),
    layers.Dropout(0.5),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(NUM_CLASSES, activation='softmax')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(), # Removed label_smoothing
    metrics=['accuracy']
)

model.summary()

"""9️⃣ Callbacks"""

callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True),
    ReduceLROnPlateau(patience=3),
    ModelCheckpoint("best_video_model.keras", save_best_only=True)
]

"""🔟 Train"""

history = model.fit(
    train_gen,
    validation_data=val_gen,
    steps_per_epoch=steps_per_epoch,
    validation_steps=val_steps,
    epochs=EPOCHS,
    callbacks=callbacks
)

"""1️⃣1️⃣ Save Deployment Model"""

model.save("final_video_action_model.keras")

model.evaluate(val_gen, steps=val_steps)

"""1️⃣4️⃣ Inference Function"""

def predict_video(video_path, model):
    frames = sample_frames_uniform_jitter(video_path, SEQUENCE_LENGTH)
    frames = frames / 255.0
    frames = np.expand_dims(frames, axis=0)

    prediction = model.predict(frames)
    class_idx = np.argmax(prediction)
    confidence = float(np.max(prediction))

    return index_to_label[class_idx], confidence

"""Inference Pipeline Test"""

predict_video("/content/UCF101/test/v_CricketShot_g06_c05.avi", model)

"""## using a sample video of cricket from outside the dataset"""

predict_video("/content/cricket_sample.mp4", model)

"""## using a sample video of ShavingBeard from outside the dataset"""

predict_video("/content/ShavingBeard_sample.mp4", model)